export const ADD_INGRIDIENT = 'ADD_INGRIDIENT';
export const DELETE_INGRIDIENT = 'DELETE_INGRIDIENT';
export const UPDATE_PURCHASABLE = 'UPDATE_PURCHASABLE';
export const SET_INGRIDIENTS = 'SET_INGRIDIENTS';
export const FETCH_INGRIDIENT_FAILED = 'FETCH_INGRIDIENT_FAILED';
export const PURCHASE_BURGER_START ='PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS ='PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL ='PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const  FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';

export const AUTH_START ='AUTH_START';
export const AUTH_SUCCESS ='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REDIRECT = 'AUTH_REDIRECT'